class EnglishText {
  static const Map<String, String> localizationValues = {
    "title": "Food Steps",
    "empty_string": "",
    "api_exception":
        "We are working on your request. Please try after sometime.",
    "timeout_exception":
        "We detect slow internet connection at your end. Please go to a good internet zone and try again.",
    "socket_exception": "Please check your internet connection.",
    "parse_exception":
        "There is a problem while fetching data. Please contact support.",
    "login": "LOGIN",
    "user_not_found": "User not found",
    "cancelCapital": "CANCEL",
    "want_to_logout": "Are you sure, you want to logout?",
    "logoutCapital": "Logout",
    "session_expired": "Session expired",
    "ok": "Ok",
    "welcome": "Welcome!",
    "login_info":
        "Kindly login to the GO-Share App using your registered email address.",
    "email": "Email",
    "first_name": "First Name",
    "last_name": "Last Name",
    "email_address": "Email Address",
    "password": "Password",
    "forgot_password": "Forgot Password",
    "question_mark": "?",
    "forgot_password_info":
        "Enter your registered email address below & we'll send you a verification code to reset your password.",
    "send_verification_link": "SEND VERIFICATION LINK",
    "awesome": "Awesome",
    "next": "Next",
    "forgot_password_link_send_success_message":
        "Your link has been successfully send to your mail",
    "profile": "Profile",
    "enable_notifications": "Enable Notification",
    "bluetooth": "Bluetooth",
    "location": "Location",
    "i_agree_to": "I agree to ",
    "terms_and_conditions": "Terms & Conditions",
    "terms_and_condition": "Terms and Condition",
    "reservation": "Reservation",
    "reservation_desc":
        "Experience effortless mobility wherever you go by making a car reservation at any time. Deliver the vehicle after the journey at your convenience.",
    "lock_unlock": "Lock/ Unlock",
    "lock_unlock_desc":
        "You can always lock a car and then unlock it whenever it's convenient for you. Check fuel and battery percentage of a car at any given point of time.",
    "reservation_directory": "Reservation Directory",
    "reservation_directory_desc":
        "Keep track of your ongoing, past and up-coming reservations along with the vehicle up to date information. Also Cancel the upcoming reservation.",
    "view_description": "View Description",
    "skip": "Skip",
    "got_it": "Got It",
    "notification_off_title":
        "Are you sure you want to switch off Notification?",
    "notification_off_desc":
        "In the future, you will be restricted from receiving notifications.",
    "bluetooth_off_title": "Are you sure you want to switch off Bluetooth?",
    "bluetooth_off_desc":
        "You won't be able to lock/unlock the car if you switch off the bluetooth",
    "location_off_title": "Are you sure you want to enable Location?",
    "location_off_desc":
        "You won't be able to locate the nearby cars around you",
    "no": "No",
    "yes": "Yes",
    "user_agreement": "User Agreement",
    "terms_and_conditions_title": "General Terms and Conditions efl",
    "i_agree_terms_and_conditions": "I AGREE TO TERMS AND CONDITIONS",
    "allow_location": "Allow Location",
    "allow_location_desc": "We need your permission to access your location",
    "do_not_allow": "Do Not Allow",
    "reserve": "Reserve",
    "reservation_start_time": "Reservation Start Time",
    "reservation_end_time": "Reservation End Time",
    "reserve_now": "Reserve: now",
    "tips_and_useful_features": "Tips & Useful features",
    "tips_and_useful_features_desc":
        "This app is more than just a journey planner. We are happy to help you get more out of the app.",
    "view_tips": "View Tips",
    "home": "Home",
    "reservations": "Reservations",
    "more": "more",
    "reserve_for_one_hour": "Reserve for 1 hour",
    "reserve_for_two_hour": "Reserve for 2 hour",
    "reserve_for_three_hour": "Reserve for 3 hour",
    "reserve_for_four_hour": "Reserve for 4 hour",
    "ongoing_reservation": "On-Going Reservation",
    "upcoming_reservation": "Upcoming Reservation",
    "past_reservation": "Past Reservation",
    "booking_id": "Booking ID",
    "recommended_for_you": "recommended_for_you",
    "your_reservation_has_been_confirmed":
        "Your reservation has been confirmed",
    "lock": "Lock",
    "unlock": "Unlock",
    "parked": "Parked",
    "fuel": "Fuel",
    "away": "away",
    "drop_off": "Drop Off",
    "pick_up": "Pick Up",
    "fuel_consumption": "Fuel Consumption",
    "distance_travelled": "Distance Travelled",
    "cancel_reservation": "Cancel Reservation",
    "reservation_cancel_title":
        "Are you sure you want to cancel this reservation?",
    "reservation_cancel_desc":
        "Your ride will be cancel if you tap on a yes button. Are you sure for this action",
    "logout_desc": "Are you sure you want to logout?",
    "change_password": "Change Password",
    "get_help": "Get Help",
    "send_feedback": "Send Feedback",
    "distance_m_unit": "m",
    "distance_km_unit": "km",
    "fuel_consumption_unit": "KWh",

    "submit": "Submit",
    "forgot_your_password": "Forgot your password?",
    "reset_your_password_here": "Reset your password here",
    "reset_your_password": "Reset your password?",
    "resend": "Resend",
    "enter_otp_you_received": "Enter the OTP you've received",
    "otp_reset_info": "OTP for resetting your password have been send to ",
    "incorrect_otp": "Incorrect OTP",
    "add_new_password": "Add new password",
    "enter_your_new_password": "Enter your new password",
    "new_password": "New password",
    "confirm_new_password": "Confirm new password",
    "include_upper_case_letter": "Include Upper case letter.",
    "include_numeric": "Include numeric letter.",
    "include_special_symbol": "Include special symbol.",
    "save_new_password": "Save new password",
    "change_your_password": "Change your password?",
    "instruction_to_add_new_password":
        "Please include below security points to create a strong password",
    "back_to_login": "Back to Login",
    "password_reset_successfully": "Password Reset Successfully",
    "your": "your",
    "password_reset_message":
        "account password reset successfully now you can login with new password",

    ///[Edited By Anuj Semwal]
    "get_machine_loan": "Get a Machine Loan that is Easy & Quick",
    "get_solar_loan": "Rooftop Solar Loans Made Easy Affordable",
    "get_business_loan":
        "Business Loan Online for Small Business Owners & MSMEs",
    "continue": "Continue",
    "or": "OR",
    "login_using": "Login using",
    "enter_phone_number": "Enter phone number",
    "do_not_have_an_account": "Don’t have an account?",
    "log_in_as_guest": "Login as a Guest",
    "log_in_using_email": "Login using email address",
    "log_in_as_emp": "Log in as a Employee",
    "loans_details": "Loans Details",
    "loan_against_property": "Loan Against Property",
    "loan_id": "Loan ID",
    "utilised_amount": "Utilised Amount",
    "available_limit": "Available Limit",
    "repayment_tenure": "Repayment Tenure",
    "annualised_rate_of_interest": "Annualised Rate of Interest",
    "loan_amount": "Loan Amount",
    "next_due_eMI_Amount": "Next Due EMI Amount",
    "pay_eMI": "Pay EMI",
    "emi_details": "EMI Details",
    "select": "Select",
    "month": "Month",
    "emi_amount": "EMI Amount",
    "selected_emi": "Selected EMI",
    "pay": "Pay",
    "status": "Status",
    "closed": "Closed",
    "loan_date": "Loan Date",
    "duration": "Duration",
    "things_you_can_do": "Things you can do",
    "view_document": "View Document",
    "loan_details": "Loan Details",
    "bank_details": "Bank Details",
    "fee_charges": "Fee & charges",
    "number_of_emi_paid": "Number of eMI’s Paid",
    "eMI_start_date": "EMI Start Date",
    "emi_end_date": "EMI End Date",
    "previous_eMI_amount": "Previous EMI Amount",
    "loan_amount_paid_till_date": "Loan Amount Paid till date",
    "disbursement_date": "Disbursement date",
    "bank_name": "Bank Name",
    "bank_account_number": "Bank Account Number",
    "bank_IFSC": "Bank IFSC",
    "applied_date": "Applied Date",
    "apply": "Apply",
    "loan_tenure": "Loan Tenure",
    "follow_up": "Follow Up",
    "adhaar_card": "Adhaar Card",
    "adhaar_info": "Adhaar , Unique Identification Authority",
    "pan_info": "Permanent account number (PAN)",
    "pan_card": "PAN Card",
    "address_proof": "Address Proof",
    "address_info": "Telephone Bill, Electricity Bill, Etc",
    "add_another_doc": "Add Another Document",
    "upload_any_proof": "Upload any proof",
    "documents": "Documents",
    "documents_info_for_close_loan":
        "Select the type of payment towards your Loan Accoun Number -",
    "phone_number": "Phone Number",
    "dob": "Date Of Birth",
    "saved_address": "Saved Address",
    "save": "Save",
    "help_us": "Help Us",
    "faq": "FAQs",
    "add_details": "Add Details",
    "add_sec_num": "Add Secondary Phone number",
    "add_additional_num": "Add Additional Phone number",
    "add_additional_email": "Add Additional email",
    "add_sec_email": "Add Secondary Email",
    "log_out": "Log Out",
    "profile_incomplete": "PROFILE INCOMPLETE",
    "profile_incomplete_warning_text":
        "Please complete your profile to apply for new loan",
    "delete_account": "Delete account",
    "name": "Name",
    "thanks_description": "Someone from our team will soon contact you",
    "primary_email_id": "Primary Email Id",
    "enter_name": "Enter name",
    "email_id": "Email Id",
    "create_password": "Create Password",
    "enter_email_id": "Enter email Id",
    "contact_us": "Contact Us",
    "about_us": "About Us",
    "privacy_policies": "Privacy Policies",
    "term_and_condition": "Term & Condition",
    "report_query": "Report Query",
    "location_and_notification": "Location & Notification",
    "location_services": "Location Services",
    "manage_notification": "Manage Notifications",
    "helpline_numbers": "Helpline Numbers",
    "LOG_OUT": "LOGOUT",
    "confirmation_logout": "Are you sure you want to logout.",
    "confirmation_delete_account":
        "Are you sure you want to Delete you account.",
    "confirmation_delete_co_applicant":
        "Are you sure you want to Delete this Co-Applicant.",
    "confirmation_delete_guarantor":
        "Are you sure you want to Delete this Guarantor.",
    "locate_nearby": "Locate Nearby Branches",
    "nach_mandate": "NACH Mandate",
    "date": "Date",
    "view_detail": "View detail",
    "update_NACH": "Update NACH",
    "loan_account_number": "Loan Account number",
    "verify_email": "Verify your email",
    "change_email_id": "Change email Id",
    "did_not_receive_code": "Didn’t receive a code?",
    "verify": "Verify",
    "change_number": "Change Number",
    "mobile_number": "Mobile Number",
    "verify_number": "Verify your Number",
    "login_using_number": "Login using phone number",
    "forgot_pass_hint":
        "Don’t worry it happens. Please enter the mobile number or email address associated with your account.",
    "enter_mobile_or_email": "Enter mobile number or email address",
    "enter_mobile": "Enter mobile number",
    "otp_sent_on_mobile": "OTP sent on Mobile number",
    "enter_otp": "Enter OTP",
    "create_acc": "Create an account",
    "create_acc_hint": "Hello there, sign up to continue.",
    "existing_loan": "Existing Loan",
    "applied_loan": "Applied Loan",
    "closed_loan": "Closed Loan",
    "others": "Others",
    "overdue_amount": "Overdue Amount",
    "make_payment": "Make Payment",
    "go_to_loan_details": "Go to Loan Details",
    "part_pre_payment": "Part Pre-Payment",
    "advance_eMI": "Advance EMI",
    "full_payment": "Full Payment/ Foreclosure",
    "part_pre_payment_content": "Pay part of the principal Outstanding Amount",
    "advance_eMI_content": "Make payment of upto 5 EMI’s in advance",
    "full_payment_content": "Pay remaining principal outstanding loan amount",
    "select_the_type_acc_num":
        "Select the type of payment towards your Loan Accoun Number - ",
    "loan_closure_date": "Loan Closure date",
    "current_bank_nach_Details": "Current Bank NACH Details",
    "max_emi_available": "Maximum EMI Available",
    "update_new_nach": "Update New NACH",
    "thank_you": "Thank You",
    "nach_update_thank_quote":
        "Your NACH request has been received. Our backend team will review and share the confirmation shortly",
    "please_enter_email_pass": "Please Enter Email And Password",
    "please_enter_email": "Please Enter Email Id",
    "please_enter_pass": "Please Enter Password",
    "please_enter_new_pass": "Please Enter New Password",
    "please_enter_confirm_pass": "Please Enter Confirm Password",
    "please_enter_valid_pass": "Please Enter Valid Password",
    "does_not_match_pass": "Password does not match",
    "mobile_number_req": "Mobile number is required",
    "valid_phone_no_error": "Please enter valid number",
    "valid_otp": "Please enter valid otp",
    "statement_of_acc": "Statement of Accounts",
    "repayment_schedule": "Repayment Schedule",
    "interest_certificate": "Interest Certificate",
    "no_loan_text": "Sorry! No Existing loans",
    "select_loan_amount": "Select Loan Amount",
    "select_tenure": "Select Tenure",
    "please_enter_the_loan_amount": "Please enter the loan amount ",
    "no_loan_des_text": "Please complete your profile to apply a new loan.",
    "make_payment_info":
        "Select the type of payment towards your Loan Accoun Number - ",
    "active_loans": "Active Loans",
    "pan_details": "PAN Details",
    "pan": "PAN",
    "enter_pan": "Enter PAN",
    "enter_aadhaar": "Enter Aadhaar Number",
    "aadhaar_details": "Aadhaar Details",
    "address": "Address",
    "enter_address": "Enter Address",
    "aadhaar": "Aadhaar",
    "gender": "Gender",
    "father_name": "Father’s Name",
    "address_line": "Address Line ",
    "state": "State",
    "district": "District",
    "city": "City",
    "upload": "Upload",
    "upload_address_proof": "Upload Address Proof",
    "residential_status": "Residential Status",
    "select_gender": "Select Gender",
    "select_state": "Select State",
    "select_district": "Select District",
    "select_city": "Select City",
    "select_residential_status": "Select Residential Status",
    "enter_your_address": "Enter your present address details (Optional)",
    "enter_your_details":
        "Enter your PAN details to complete your loan request",
    "enter_applicant_details": "Enter Applicant Details",
    "view_all": "View All",
    "get_started": "Get Started",
    "new_purchase": "New Purchase",
    "refinance": "Refinance",
    "secured_loan": "Secured Loan",
    "unsecured_loan": "UnSecured Loan",
    "lic": "LIC",
    "hey": "Hey",
    "salaried": "Salaried",
    "edit": "Edit",
    "delete": "Delete",
    "vehicle": "Vehicle",
    "done": "Done",
    "adhaar_number": "Adhaar Number",
    "pan_acc_num": "Permanent Account Number",
    "pan_acc_num_hint":
        "Or PAN is a 10-Character alphanumeric located at the bottom of your PAN Card",
    "adhaar_hint":
        "Or Adhaar number is a 12-digit unique identity number located at the bottom of your Adhaar Card",
    "machine": "Machine",
    "guarantor": "Guarantor!",
    "list_of_guarantor": "Here is the list of Guarantor!",
    "entity_name": "Entity Name",
    "enter_co_applicant_details": "Enter Co-Applicant Details",
    "enter_guarantor_details": "Enter Guarantor Details",
    "enter_co_applicant_details_text":
        "Enter Co-Applicant details to complete your loan request",
    "enter_guarantor_details_text":
        "Enter guarantor details to complete your loan request",
    "date_of_incorporation": "Date of Incorporation",
    "co_applicants": "Co-applicants!",
    "add_co_applicants": "Add Another",
    "enter_collateral_details_text":
        "Enter your Collateral details to complete your loan request",
    "list_of_co_applicants": "Here is the list of CoApplicants",
    "help_us_content": "Just a few more steps to complete your loan request",
    "self_employed": "Self Employed",
    "self_employed_content":
        "You seems to be a Self Employed.  Please confirm & select your occupation.",
    "salaried_content":
        "You seems to be a salaried employee. Please confirm & select your occupation.",
    "lap_collateral_details": "Collateral Details (LAP)",
    "property_type": "Property Type",
    "back": "Back",
    "category": "Category",
    "type_description": "Type Description",
    "max_300_words": "Max:300 Words",
    "credit_score": "Credit Score",
    "rented": "Rented",
    "owned": "Owned",
    "property_value": "Property Value (Per Sq.Ft.)",
    "area_of_property": "Area of Property (Sq. Ft.)",
    "upload_property_pics": "Upload Property Pictures",
    "property_address": "Property Address",
    "residential": "Residential",
    "industrial": "Industrial",
    "commercial": "Commercial",
    "permanent": "Permanent",
    "present": "Present",
    "new": "New",
    "enter_new_add": "Enter New Address",
    "collateral_details": "Collateral Details",
    "collateral_type": "Collateral Type",
    "property_lap": "Property Lap",
    "add_another_collateral": "Add Another Collateral",
    "add_bank_account": "Add Bank Account",
    "back_to_home": "Back to Home",
    "eligible_amount": "Eligible Amount",
    "apply_for_eligible_loan": "Apply for the Eligible Loan Amount ",
    "or_apply_for_amount": "or Apply for the amount ",
    "choose_an_option": "Choose one option",
    "new_loan_application": "New loan application",
    "loan_application_id": "Loan Application ID",
    // "loan_application_is_under_review":"Your Loan Application is under review and our team will reach out to you very soon.",
    "loan_application_is_under_review":
        "We are assessing your application. Be assured our team will reach out to you soon",
    "loan_application_is_approved": "Your Loan Application has been approved",
    "you_are_eligible": "Your are eligible for a loan amount of",
    "congratulation": "Congratulation",
    "is_machine_available": "Is Machine Available?",
    "select_your_occupation": "Select your occupation.",
    "occupation": "Occupation",
    "i_agree_to_consent_on": "I agree to consent on",
    "and": "And",
    "require_noc": "Require NOC",
    "require_ndc": "Require NDC",
    "short_closure_calculation": "Short Closure Calculation",
    "regular_closure_calculation": "Regular Closure Calculation",
    "SOA/IRR/IPC": "SOA/IRR/IPC",
    "refund": "Refund",
    "general_query": "General Query",
    "original": "Original",
    "duplicate": "Duplicate",
    "tds_refund": "TDS Refund",
    "EMI_excess_refund": "EMI Excess Refund",
    "closure_refund": "Closure Refund",
    "other_refund": "Other Refund",
    "sanction_letter_require": "Sanction Letter Require.",
    "outstanding_require": "Outstanding Require/ Exposure Details Require",
    "track_record_require": "Track Record Require",
    "you_did_it": "You Did it",
    "under_review": "Under Review",
    "your_loan_under_review_be_sure_team_will_back":
        "Your loan application is still under review. Be assured our team will soon reach out to you.",
    "just_need_to_enter_adhaar": "You just need to enter your Adhaar details!",
    "be_with_us": "Be with us",
    "hey_there": "Hey There",
  };
}
